#!/bin/bash
# jmux first-run welcome screen
# Called via: display-popup -E "welcome.sh"

BOLD="\033[1m"
DIM="\033[2m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RESET="\033[0m"

clear
echo ""
echo -e "  ${GREEN}${BOLD}Welcome to jmux${RESET}"
echo -e "  ${DIM}The terminal workspace for agentic development${RESET}"
echo ""
echo -e "  ${DIM}────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${BOLD}Essential keybindings${RESET}"
echo ""
echo -e "  ${GREEN}Ctrl-Shift-Up/Down${RESET}     Switch between sessions"
echo -e "  ${GREEN}Ctrl-a${RESET} then ${GREEN}n${RESET}          New session"
echo -e "  ${GREEN}Ctrl-a${RESET} then ${GREEN}c${RESET}          New window (tab)"
echo -e "  ${GREEN}Ctrl-a${RESET} then ${GREEN}|${RESET}          Split pane horizontally"
echo -e "  ${GREEN}Ctrl-a${RESET} then ${GREEN}-${RESET}          Split pane vertically"
echo -e "  ${GREEN}Shift-Arrow${RESET}            Move between panes"
echo -e "  ${GREEN}Ctrl-a${RESET} then ${GREEN}i${RESET}          Settings"
echo ""
echo -e "  ${DIM}────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${BOLD}The sidebar${RESET} on the left shows all your sessions."
echo -e "  ${GREEN}●${RESET} Green dot = new output    ${YELLOW}!${RESET} Orange = needs review"
echo -e "  Click a session to switch to it."
echo ""
echo -e "  ${DIM}────────────────────────────────────────────${RESET}"
echo ""
echo -e "  ${BOLD}Next steps${RESET}"
echo ""
echo -e "  ${CYAN}1.${RESET} Try ${GREEN}Ctrl-a n${RESET} to create a new session"
echo -e "  ${CYAN}2.${RESET} Run ${GREEN}jmux --install-agent-hooks${RESET} for Claude Code notifications"
echo -e "  ${CYAN}3.${RESET} Full guide: ${DIM}github.com/jarredkenny/jmux/blob/main/docs/getting-started.md${RESET}"
echo ""
echo -e "  ${DIM}Press any key to start${RESET}"
read -rsn1
